# Generated by Django 3.2.4 on 2021-08-10 14:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="complex",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="estate.complex",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 10, 14, 17, 13, 34011)
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="riser",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="section",
            name="floor_count",
            field=models.PositiveIntegerField(),
        ),
    ]
