# Generated by Django 3.2.4 on 2021-08-10 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0002_auto_20210810_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 10, 15, 1, 58, 46521)
            ),
        ),
    ]
