# Generated by Django 3.2.4 on 2021-08-11 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_advertisement_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 11, 4, 53, 38, 61328)),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='furnish',
            field=models.CharField(choices=[('Черновая отделка', 'Черновая отделка'), ('Евроремонт', 'Евроремонт'), ('Ремонт от строителей', 'Ремонт от строителей')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment_options',
            field=models.CharField(choices=[('Ипотека', 'Ипотека'), ('Кредит', 'Кредит'), ('Рассрочка', 'Рассрочка'), ('Покупка', 'Покупка')], max_length=50),
        ),
    ]
