# Generated by Django 3.2.4 on 2021-08-11 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0004_auto_20210811_0453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 11, 5, 58, 20, 545019)
            ),
        ),
    ]
