# Generated by Django 3.2.4 on 2021-08-15 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0015_auto_20210815_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 15, 7, 48, 50, 936179)
            ),
        ),
    ]
