# Generated by Django 3.2.4 on 2021-08-15 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0019_alter_advertisement_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 15, 11, 24, 13, 685732)
            ),
        ),
    ]
