# Generated by Django 3.2.4 on 2021-08-16 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0020_alter_advertisement_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="expiration",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 16, 15, 17, 32, 787059)
            ),
        ),
    ]
