# Generated by Django 3.2.4 on 2021-08-16 16:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.users.services.image_services


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0026_alter_advertisement_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='section',
        ),
        migrations.RemoveField(
            model_name='riser',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='section',
        ),
        migrations.AddField(
            model_name='complaint',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 16, 36, 25, 206264)),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='corpus',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor_schema',
            field=models.ImageField(upload_to=src.users.services.image_services.UploadToPathAndRename('images/apartment/floor_schema/')),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='riser',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='schema',
            field=models.ImageField(upload_to=src.users.services.image_services.UploadToPathAndRename('images/apartment/schema/')),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Corpus',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Riser',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
