# Generated by Django 3.2.4 on 2021-08-17 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210816_1610'),
        ('estate', '0028_alter_advertisement_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 9, 0, 5, 862462)),
        ),
        migrations.AlterField(
            model_name='complex',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_contact', to='users.contact'),
        ),
    ]
