# Generated by Django 3.2.4 on 2021-08-17 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0031_auto_20210817_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 14, 15, 54, 515449)),
        ),
    ]
