# Generated by Django 3.2.4 on 2021-08-19 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0034_auto_20210818_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexdocument',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 19, 4, 49, 14, 653819)),
        ),
    ]
