# Generated by Django 3.2.4 on 2021-08-19 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0035_auto_20210819_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 19, 4, 49, 58, 138718)),
        ),
    ]
