# Generated by Django 3.2.4 on 2021-08-20 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0037_auto_20210819_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 5, 18, 30, 232798)),
        ),
        migrations.AlterField(
            model_name='complex',
            name='distance_to_sea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complexbenefits',
            name='complex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complex_benefits', to='estate.complex'),
        ),
    ]
