# Generated by Django 3.2.4 on 2021-08-20 09:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0039_auto_20210820_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 9, 21, 27, 512065)),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.complex'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='corpus',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='map_lng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='moderation_status',
            field=models.CharField(choices=[('Проверяется', 'Проверяется'), ('Отклонено', 'Отклонено'), ('Принято', 'Принято')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='riser',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
