# Generated by Django 3.2.4 on 2021-08-20 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0040_auto_20210820_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 9, 24, 21, 803350)),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
