# Generated by Django 3.2.4 on 2021-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0046_alter_advertisement_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expiration',
            field=models.DateField(auto_now=True),
        ),
    ]
