# Generated by Django 3.2.4 on 2021-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0048_auto_20210820_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='complex_relation_status',
            field=models.CharField(choices=[('Не часть ЖК', 'Не часть ЖК'), ('Проверяется', 'Проверяется'), ('Часть ЖК', 'Часть ЖК'), ('Отклонено', 'Отклонено')], default='Не часть ЖК', max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='moderation_status',
            field=models.CharField(choices=[('Проверяется', 'Проверяется'), ('Отклонено', 'Отклонено'), ('Принято', 'Принято')], default='Проверяется', max_length=50),
        ),
    ]
