# Generated by Django 3.2.4 on 2021-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0051_auto_20210822_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
