# Generated by Django 3.2.4 on 2021-08-05 12:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that username already exists.'}, max_length=128, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
