# Generated by Django 3.2.4 on 2021-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_alter_user_username")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Phone number"
            ),
        )
    ]
