# Generated by Django 3.2.4 on 2021-08-09 13:08

from django.db import migrations, models
import src.users.services.image_services
import src.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20210805_1238")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.users.services.image_services.UploadToPathAndRename(
                    "/home/roman/GitHub/SwipeApp/media/images/users/avatars"
                ),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="forward_to_agent",
            field=models.BooleanField(
                default=False,
                help_text="Определяет необходимо ли переадресовывать звонки и сообщения агенту. ",
                verbose_name="Переключить звонки и сообщения на агента",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(
                default=True,
                help_text="Определяет считать ли пользователя Застройщиком. ",
                verbose_name="Статус застройщика",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=True,
                help_text="Определяет может ли пользователь входить в систему",
                verbose_name="Статус верификации номера мобильного телефона",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("Мне", "Мне"),
                    ("Мне и агенту", "Мне и агенту"),
                    ("Агенту", "Агенту"),
                    ("Отключить", "Отключить"),
                ],
                default="Мне",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="Статус пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="Статус сотрудника",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[src.users.models.validate_international_phonenumber],
                verbose_name="Номер телефона",
            ),
        ),
    ]
