# Generated by Django 3.2.4 on 2021-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210809_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blacklisted",
            field=models.BooleanField(
                default=False, verbose_name="Статус нахождения в черном списке"
            ),
        ),
    ]
