# Generated by Django 3.2.4 on 2021-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0003_alter_advertisement_expiration"),
        ("users", "0008_user_is_blacklisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_apartments",
            field=models.ManyToManyField(to="estate.Apartment"),
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_complex",
            field=models.ManyToManyField(to="estate.Complex"),
        ),
    ]
