# Generated by Django 3.2.4 on 2021-08-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_message_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
