# Generated by Django 3.2.4 on 2021-08-15 07:38

from django.db import migrations, models
import src.users.services.image_services


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20210814_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to=src.users.services.image_services.UploadToPathAndRename(
                    "files/messages/"
                )
            ),
        ),
    ]
