# Generated by Django 3.2.4 on 2021-08-15 08:21

from django.db import migrations, models
import src.users.services.image_services


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_contact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.users.services.image_services.UploadToPathAndRename(
                    "images/users/avatars"
                ),
            ),
        ),
    ]
