# Generated by Django 3.2.4 on 2021-08-16 15:53

from django.db import migrations, models
import src.users.services.image_services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210816_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=src.users.services.image_services.UploadToPathAndRename('images/service_centers/')),
        ),
    ]
