# Generated by Django 3.2.4 on 2021-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_notary_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='map_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
