# Generated by Django 3.2.4 on 2021-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0025_alter_advertisement_expiration'),
        ('users', '0026_auto_20210816_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_apartments',
            field=models.ManyToManyField(to='estate.Apartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_complex',
            field=models.ManyToManyField(to='estate.Complex'),
        ),
    ]
